config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'

  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"

  resources :products
  resources :upvotes, only: [ :create, :destroy ]
  resources :messages, only: [ :create, :index, :show, :new ]

  # Read action routes
  # get "/messages"     => "messages#index"
  # get "/messages/:id" => "messages#show"
  # get "/messages/new" => "messages#new"
  # post "/messages"    => "messages#create"



  # # Read action routes
  # get "/products" => "products#index"
  # get "/products/:id" => "products#show"

  # # Create action routes
  # get "/products/new" => "products#new" #affficher le formulaire à remplir
  # post "/products" => "products#create"

  # # Update action routes
  # get "/products/:id/edit" => "products#edit"
  # patch "/products/:id" => "products#update"

  # # Delete action routes
  # delete "/products/:id" => "products#destroy"





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_attachment :photo
  belongs_to :user
  has_many :upvotes
  has_many :messages

  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :category, inclusion: { in: %w(tech education design),
    message: "%{value} is not a valid category" }
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user, uniqueness: { scope: :product }
end

app/models/user.rb
class User < ApplicationRecord
  has_attachment :avatar
  has_many :products
  has_many :upvotes
  has_many :messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def voted_for?(product)
    #  if Upvote.where(product_id: product.id).where(user_id: current_user.id).any?
    if Upvote.where("product_id = ? AND user_id = ?", product.id, self.id).any?
       return true
     else
      return false
     end

#product.upvotes.where(user: self).any?

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user! #liste blanche

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
   # devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params_message)
    @message.user = current_user
    if @message.save then redirect_to messages_path
    else render :new
    end
  end

  def private params_message
    params.require(:message).permit(:user, :content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @today = Date.today
  end
  def team
    @members = ["Bob" , "Romain", "Seb"]
  end
  def join_us
    render plain: "Send us a mail"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_product, only: [ :show, :edit, :update, :destroy]

  def index
    if params[:category]
      @products = Product.where(category: params[:category])
    else
      @products = Product.all
    end
  end

  def show
    # @product = Product.find(params[:id])
    @messages = Message.where(product: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save == true
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    # @product = Product.find(params[:id])
  end

  def update
    # @product = Product.find(params[:id])
    if @product.user == current_user
      if @product.update(product_params)
        redirect_to products_path
      else render :edit
      end
    else
      flash[:alert]= "Action impossible, ceci n'est pas votre produit"
      render :edit
    end
  end

  def destroy
      # @product = Product.find(params[:id])
      if @product.destroy
          redirect_to products_path
      else render plain: "Impossible de supprimer"
      end
  end

  private
  def product_params
    params.require(:product).permit(:name, :url, :tagline, :category, :photo)
  end

  def find_product
     @product = Product.find(params[:id])
  end


end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController


  def create
    @product = Product.find( params[:product_id] )
    @product.upvotes.create! user: current_user

    respond_to do |format|
      format.html {redirect_to products_path}
      format.js
    end

    # autre méthode pour insérer data en base (méthode Floflo)
    #@upvote = Upvote.new(user_id: current_user.id, product_id: params[:product_id])
    #@upvote.save

  end

  def destroy
    upvote = Upvote.find(params[:id])
    @product = upvote.product
    upvote.destroy
    respond_to do |format|
      format.html {redirect_to products_path}
      format.js
    end

    # if @product.upvote.destroy
    # then redirect_to products_path
    # else render flash[:alert] = "Impossible de supprimer"
    # end

  end


  # private
  # def upvote_params
  # params.require(:upvote).permit(:user_id, :product_id)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, @product do |f| %>
  <%= @message.errors.full_messages %>
  <%= f.input :content, placeholder: "ici votre message"%>
  <%= f.input :product %>
  <%= f.button :submit ,"Poster", class: "btn btn-primary" %>
<% end %>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <ul>
        <%= @messages.each do |message| %>
          <li>
            <%= message.user.email %> - <%= message.content %>
            <%= link_to "voir le message", message_path(message) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="contain">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Ajouter un message</h1>

      <%= render "form" %>
      <%= link_to "Cancel", products_path, class: "btn btn-info" %>

    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <h1>Le message est</h1>
        <%= @message.content %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(' <%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>Lobady Lobada</h1>
    <p>We have <strong> lots of new products </strong> on <%= @today %></p>
    <%= link_to "Accéder aux produits", products_path,class: "btn btn-primary btn-lg" %>
    <%=  link_to "Accéder aux messages", messages_path, class: "btn btn-warning btn-lg" %>
  </div>
</div>


<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
       <%= link_to "Design", products_path(category: "design"), class:"card-category" %>
    </div>
    <div class="col-xs-12 col-sm-4">
       <%= link_to "Tech", products_path(category: "tech"), class:"card-category" %>
    </div>
    <div class="col-xs-12 col-sm-4">
       <%= link_to "Education", products_path(category: "education"), class:"card-category" %>
    </div>
  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <h2>oulala</h2>

  <h1> Meet the team</h1>

    <ul>
<%= cl_image_tag "m0qygpbltkvfknbxzjdj", height: 100, width: 400, crop: :fill %>

      <%= @members.each do |member|%>
      <li> Member: <%= member %> </li>
      <% end %>

    </ul>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= @product.errors.full_messages %>
  <%= f.input :name, placeholder: "Kudoz", label: "Which product?" %>
  <%= f.input :url, placeholder: "http://kudoz.com", label: "Which url?" %>
  <%= f.input :tagline, placeholder: "Ceci est la catch phrase", label: "What tagline?" %>
  <%= f.input :category, collection: ["tech", "education", "design"], prompt: "Which category?" %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit ,"Sauvegarder", class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<div class="contain">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Editer le produit</h1>


      <%= render "form" %>

      <!--       <%= simple_form_for @product do |f| %>
        <%= f.input :name, placeholder: "Kudoz", label: "Which product?" %>
        <%= f.input :url, placeholder: "http://kudoz.com", label: "Which url?" %>
        <%= f.button :submit ,"Sauvegarder", class: "btn btn-primary" %>
      <% end %> -->

        <%= link_to "Cancel", product_path(@product), class: "btn btn-info" %>
      <!-- <form action="/products" method = "post">
        <div class="form-group">
          <label for="name">Choisissez un nom de produit</label>
          <input type="text" name="product[name]" class="form-control" placeholder="Kudoz" id="name">
        </div>
        <div class="form-group">
          <label for="url">Quelle url?</label>
          <input type="text" name = "product[url]" class="form-control" placeholder = "http://kudoz.com" id="url">
        </div>
        <input type="submit" value="Ajouter" class="btn btn-primary">
      </form> -->

    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container text-center">


<!-- <p>
  <%= link_to "Revenir à l'acceuil", root_path, class: "btn btn-primary" %>
  <%= link_to "Créer nouveau produit", new_product_path, class: "btn btn-success" %>
</p> -->

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center">Les produits</h1>

      <% @products.each do |product| %>

          <div class="product">

          <div class="upvote-container" id = "product-<%= product.id %>">
            <%= render 'upvotes/show', product: product %>
          </div>

          <% if product.photo? %>
          <%= cl_image_tag product.photo.path, crop: :fill, class:"product-image" %>
          <% else %>
          <img src="http://unsplash.it/300/200" alt="kudoz" class="product-image hidden-xs">
          <% end %>

          <div class='product-body'>
            <h3> <%= link_to product.name ,product_path(product) %> </h3>

            <p> <%= product.tagline %> </p>
          </div>
          <ul class="list-inline product-controls hidden-sm hidden-xs">
            <li>
              <%= link_to product_path(product) do %>
                <i class="fa fa-eye"></i>
              <% end %>
            </li>
            <li>
              <%= link_to edit_product_path(product) do %>
              <i class="fa fa-pencil"></i>
              <% end %>
            </li>
            <li>
              <%= link_to product_path(product), method: :delete do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>








    </div>
  </div>
</div>




</div>

app/views/products/new.html.erb
<div class="contain">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Ajouter un produit</h1>

      <%= simple_form_for @product do |f| %>
        <%= f.input :name, placeholder: "Kudoz", label: "Which product?" %>
        <%= f.input :url, placeholder: "http://kudoz.com", label: "Which url?" %>
        <%= f.button :submit ,"Ajouter", class: "btn btn-primary" %>
        <%= link_to "Cancel", products_path, class: "btn btn-info" %>
      <% end %>

      <!-- <form action="/products" method = "post">
        <div class="form-group">
          <label for="name">Choisissez un nom de produit</label>
          <input type="text" name="product[name]" class="form-control" placeholder="Kudoz" id="name">
        </div>
        <div class="form-group">
          <label for="url">Quelle url?</label>
          <input type="text" name = "product[url]" class="form-control" placeholder = "http://kudoz.com" id="url">
        </div>
        <input type="submit" value="Ajouter" class="btn btn-primary">
      </form> -->

    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @product.photo? ? cloudinary_url(@product.photo.path, width: 1280, crop: :fill) : image_path("background.jpg") %>');">
  <div class="banner-content">
    <h1> <%= @product.name %> </h1>
    <h2> <%= @product.tagline %> </h2>
    <h2> <%= @product.category %> </h2>
    <% if @product.user %>
      <h2> Added by: <%= @product.user.email %> </h2>
    <% end %>

    <% if @product.photo? %>
      <%= cl_image_tag @product.photo.path, width: 200 %>
    <% end %>
    <ul>
        <% @messages.each do |message| %>
          <li> <%= message.user.email %> : <%= message.content %> </li>
        <% end %>
    </ul>
    <%= link_to "Visit website", @product.url, class: "btn btn-primary" %>
    <%= link_to "Editer", edit_product_path(@product), class: "btn btn-warning" %>
    <%= link_to "Supprimer",product_path(@product), method: :delete, class: "btn btn-danger" %>
    <%= link_to "Revenir à la liste de produits", products_path, class: "btn btn-info" %>
    <%= link_to "Liker", upvotes_path, method: :post, class: "btn btn-info" %>
    <%= link_to "Poster", new_message_path, class: "btn btn-info" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> by Floflo
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "pitch.png" %>
  </a>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <% if user_signed_in? %>
            <%= link_to "All products", products_path, class: "navbar-wagon-item navbar-wagon-link"%>
            <%= link_to "Create product", new_product_path, class: "btn-medium" %>
            <%= link_to "Create message", new_message_path, class: "btn-medium" %>
            <!-- Profile picture with dropdown list -->
            <div class="navbar-wagon-item">
              <div class="dropdown">

                <% if current_user.avatar? %>
                <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class:"avatar dropdown-toggle", id:"navbar-wagon-menu", :'data-toggle' => "dropdown" %>
                <% else %>
                <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
                <% end %>

                <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                  <li><a href="#">Profile</a></li>
                  <li>
                    <%= link_to "Team", team_path %>
                  </li>
                  <li>
                    <%= link_to "Deconnexion", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </div>
            </div>
        <% else %>
          <%= link_to "Connexion", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Inscription", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </div>

      <!-- Dropdown appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Host</a></li>
            <li><a href="#">Trips</a></li>
            <li><a href="#">Messagese</a></li>
          </ul>
        </div>
      </div>
</div>

app/views/upvotes/_show.html.erb
<% if user_signed_in? %>
  <% if current_user.voted_for?(product) %>
   <%= link_to upvote_path(current_user.upvotes.where(product: product).first), remote: true, method: :delete, class:"product-upvote product-upvoted" do %>
      <div class="product-arrow"></div>
      <div class='product-count'><%= product.upvotes.size %></div>
    <% end %>
  <% else %>
    <%= link_to upvotes_path(product_id: product.id), remote: true, method: :post, class:"product-upvote" do %>
      <div class="product-arrow"></div>
      <div class='product-count'><%= product.upvotes.size %></div>
    <% end %>
  <% end %>

<% else %>
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>
      <%= product.upvotes.size %>
    </div>
  </div>
<% end %>

app/views/upvotes/create.js.erb
$('#product-<%= @product.id %>').html('<%= j render 'upvotes/show', product: @product %>')

app/views/upvotes/destroy.js.erb
$('#product-<%= @product.id %>').html('<%= j render 'upvotes/show', product: @product %>')